# Generated by Django 3.2.4 on 2021-07-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaordering', '0003_auto_20210720_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('key', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=255)),
            ],
        ),
    ]
