# Generated by Django 3.2.4 on 2022-05-14 17:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pizzaordering.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_code', models.CharField(default=pizzaordering.models.generate__base_code, max_length=15, unique=True)),
                ('base_name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('base_description', models.CharField(default='', max_length=255, null=True)),
                ('base_medium_only', models.BooleanField(default=False, verbose_name='Medium Only')),
                ('base_group', models.CharField(choices=[('dough', 'Dough'), ('sauce', 'Sauce'), ('cheese', 'Cheese'), ('topping', 'Topping')], default='dough', max_length=100)),
                ('base_type', models.CharField(choices=[('none', 'None'), ('meat', 'Meat'), ('veggie', 'Veggie'), ('cheese', 'Cheese')], default='None', max_length=255, verbose_name='Type')),
                ('base_image', models.ImageField(default=pizzaordering.models.default_image, null=True, upload_to=pizzaordering.models.get_image_filepath, verbose_name='Base Image')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('base_note', models.CharField(default='', max_length=255, null=True, verbose_name='Special Instruction')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_code', models.CharField(default=pizzaordering.models.generate__order_code, max_length=15, unique=True)),
                ('is_delivery', models.BooleanField(default=False)),
                ('is_pickup', models.BooleanField(default=False)),
                ('restaurant_location', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('delivery_location', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_finish', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecretKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('key', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_code', models.CharField(default=pizzaordering.models.generate__receipt_code, max_length=15, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('after_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='pizza_order', to='pizzaordering.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(default=pizzaordering.models.generate__product_code, max_length=15, unique=True)),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_descritpion', models.CharField(max_length=255, unique=True)),
                ('product_img', models.ImageField(default=pizzaordering.models.default_image, null=True, upload_to=pizzaordering.models.get_image_filepath, verbose_name='Product Image')),
                ('product_group', models.CharField(choices=[('none', 'None'), ('pizza', 'Pizza'), ('drink', 'Drink'), ('dipping', 'Dipping')], default='', max_length=100, null=True)),
                ('product_type', models.CharField(choices=[('none', 'None'), ('pizza', (('meat', 'Meat'), ('veggie', 'Veggie'), ('cheese', 'Cheese'))), ('drink', (('soft', 'Soft'), ('tea', 'Tea'), ('alcohol', 'Alcohol'))), ('dipping', 'None')], default='------', max_length=100, null=True)),
                ('product_size', models.CharField(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra-large', 'Extra large')], default='n', max_length=100)),
                ('product_slice', models.CharField(default='{ "small": 6, "medium": 8, "large": 10, "x-large": 12}', max_length=255, null=True)),
                ('product_is_sample', models.BooleanField(default=False)),
                ('product_carlos', models.CharField(default='{"small": 0, "medium": 0, "large": 0, "x-large": 0}', max_length=255)),
                ('product_price', models.CharField(default='{"small": 0, "medium": 0, "large": 0, "x-large": 0}', max_length=255)),
                ('product_discount', models.FloatField(default=0, verbose_name='Product Discount')),
                ('product_note', models.CharField(blank=True, default='', max_length=550, null=True)),
                ('product_created_date', models.DateTimeField(auto_now=True, verbose_name='Product Created Date')),
                ('product_updated_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Product Updated Date')),
                ('product_base', models.ManyToManyField(blank=True, related_name='product_base', to='pizzaordering.Base')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='order_pizza', to='pizzaordering.Product'),
        ),
    ]
