# Generated by Django 3.2.4 on 2021-07-20 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pizzaordering.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('amount', models.CharField(choices=[('less', 'Less'), ('more', 'More'), ('regular', 'Regular')], default='regular', max_length=20)),
                ('cheese_img', models.ImageField(default=pizzaordering.models.default_image, null=True, upload_to=pizzaordering.models.get_image_filepath, verbose_name='cheese image')),
                ('carlos', models.CharField(default='{"small": 0, "medium": 0, "large": 0, "x-large": 0}', max_length=255)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Dipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dipping_img', models.ImageField(default=pizzaordering.models.default_image, null=True, upload_to=pizzaordering.models.get_image_filepath, verbose_name='dipping image')),
                ('number', models.IntegerField(default=0)),
                ('carlos', models.IntegerField()),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('medium_only', models.BooleanField(default=False)),
                ('dough_img', models.ImageField(default=pizzaordering.models.default_image, null=True, upload_to=pizzaordering.models.get_image_filepath, verbose_name='dough image')),
                ('carlos', models.CharField(default='{"small": 0, "medium": 0, "large": 0, "x-large": 0}', max_length=255)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(default=pizzaordering.models.generate__code, max_length=15, unique=True)),
                ('is_delivery', models.BooleanField(default=False)),
                ('restaurant_location', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('delivery_location', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_finish', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dippings', models.ManyToManyField(blank=True, related_name='order_dipping', to='pizzaordering.Dipping')),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('amount', models.CharField(choices=[('less', 'Less'), ('more', 'More'), ('regular', 'Regular')], default='r', max_length=20)),
                ('sauce_img', models.ImageField(default=pizzaordering.models.default_image, null=True, upload_to=pizzaordering.models.get_image_filepath, verbose_name='sauce image')),
                ('carlos', models.CharField(default='{"small": 0, "medium": 0, "large": 0, "x-large": 0}', max_length=255)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('meat', 'Meat'), ('veggie', 'Veggie'), ('cheese', 'Cheese')], max_length=10)),
                ('topping_img', models.ImageField(default=pizzaordering.models.default_image, null=True, upload_to=pizzaordering.models.get_image_filepath, verbose_name='topping image')),
                ('carlos', models.CharField(default='{"small": 0, "medium": 0, "large": 0, "x-large": 0}', max_length=255)),
                ('part', models.CharField(choices=[('left side', 'Left Side'), ('on whole', 'On Whole'), ('right side', 'Right Side')], default='on whole', max_length=20)),
                ('amount', models.CharField(choices=[('less', 'Less'), ('more', 'More'), ('regular', 'Regular')], default='regular', max_length=20)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('after_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='pizzaordering.order')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pizza_code', models.CharField(default=pizzaordering.models.generate__code, max_length=15, unique=True)),
                ('pizza_img', models.ImageField(default=pizzaordering.models.default_image, null=True, upload_to=pizzaordering.models.get_image_filepath, verbose_name='pizza image')),
                ('pizza_type', models.CharField(default='meat', max_length=100)),
                ('size', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('x', 'Extra large')], default='s', max_length=1)),
                ('slices', models.CharField(default='{ "small": 6, "medium": 8, "large": 10, "x-large": 12}', max_length=255)),
                ('is_sample', models.BooleanField(default=False)),
                ('carlos', models.CharField(default='{"small": 0, "medium": 0, "large": 0, "x-large": 0}', max_length=255)),
                ('number', models.IntegerField(default=1, null=True)),
                ('price', models.CharField(default='{"small": 0, "medium": 0, "large": 0, "x-large": 0}', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=550, null=True)),
                ('base_cheese', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaordering.cheese')),
                ('dough', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaordering.dough')),
                ('sauce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaordering.sauce')),
                ('toppings', models.ManyToManyField(blank=True, to='pizzaordering.Topping')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(blank=True, related_name='order_pizza', to='pizzaordering.Pizza'),
        ),
    ]
