# Generated by Django 3.2.4 on 2022-05-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_descritpion',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
