# Generated by Django 3.2.4 on 2022-04-21 15:39

from django.db import migrations, models
import pizzaordering.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaordering', '0005_alter_receipt_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('medium_only', models.BooleanField(default=False, verbose_name='Medium Only')),
                ('group', models.CharField(choices=[('dough', 'Dough'), ('sauce', 'Sauce'), ('cheese', 'Cheese'), ('topping', 'Topping')], default='dough', max_length=100)),
                ('type', models.CharField(choices=[('none', 'None'), ('meat', 'Meat'), ('veggie', 'Veggie'), ('cheese', 'Cheese')], default='None', max_length=255, verbose_name='Type')),
                ('image', models.ImageField(default=pizzaordering.models.default_image, null=True, upload_to=pizzaordering.models.get_image_filepath, verbose_name='Base Image')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('carlos', models.CharField(default='{"small": 0, "medium": 0, "large": 0, "x-large": 0}', max_length=255, verbose_name='Carlos')),
                ('special_instruction', models.CharField(default='', max_length=255, null=True, verbose_name='Special Instruction')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_code', models.CharField(default=pizzaordering.models.generate__code, max_length=15, unique=True)),
                ('product_descritpion', models.CharField(max_length=255, unique=True)),
                ('product_img', models.ImageField(default=pizzaordering.models.default_image, null=True, upload_to=pizzaordering.models.get_image_filepath, verbose_name='Product Image')),
                ('product_group', models.CharField(choices=[('none', 'None'), ('pizza', 'Pizza'), ('drink', 'Drink'), ('dipping', 'Dipping')], default='', max_length=100, null=True)),
                ('product_type', models.CharField(choices=[('none', 'None'), ('pizza', (('meat', 'Meat'), ('veggie', 'Veggie'), ('cheese', 'Cheese'))), ('drink', (('soft', 'Soft'), ('tea', 'Tea'), ('alcohol', 'Alcohol'))), ('dipping', 'None')], default='------', max_length=100, null=True)),
                ('product_size', models.CharField(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra-large', 'Extra large')], default='n', max_length=100)),
                ('product_slice', models.CharField(default='{ "small": 6, "medium": 8, "large": 10, "x-large": 12}', max_length=255, null=True)),
                ('product_is_sample', models.BooleanField(default=False)),
                ('product_carlos', models.CharField(default='{"small": 0, "medium": 0, "large": 0, "x-large": 0}', max_length=255)),
                ('product_price', models.CharField(default='{"small": 0, "medium": 0, "large": 0, "x-large": 0}', max_length=255)),
                ('product_note', models.CharField(blank=True, default='', max_length=550, null=True)),
                ('product_base', models.ManyToManyField(blank=True, to='pizzaordering.Base')),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='base_cheese',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='dough',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='sauce',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dippings',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='order',
            name='is_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Cheese',
        ),
        migrations.DeleteModel(
            name='Dough',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Sauce',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='order_pizza', to='pizzaordering.Product'),
        ),
    ]
