# Generated by Django 3.2.4 on 2022-04-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaordering', '0006_auto_20220421_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dipping',
        ),
    ]
