# Generated by Django 3.2.4 on 2022-05-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaordering', '0007_delete_dipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='group',
            new_name='base_group',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='image',
            new_name='base_image',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='special_instruction',
            new_name='base_instruction',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='name',
            new_name='base_name',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='type',
            new_name='base_type',
        ),
        migrations.RemoveField(
            model_name='base',
            name='carlos',
        ),
    ]
