# Generated by Django 3.2.4 on 2022-05-07 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaordering', '0008_auto_20220506_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Product Created Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.FloatField(default=0, verbose_name='Product Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_updated_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Product Updated Date'),
        ),
    ]
