# Generated by Django 3.2.4 on 2022-05-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaordering', '0009_auto_20220507_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='medium_only',
            new_name='base_medium_only',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='base_instruction',
            new_name='base_note',
        ),
    ]
