# Generated by Django 3.2.4 on 2022-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaordering', '0010_auto_20220512_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='base_descritpion',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
