# Generated by Django 3.2.4 on 2022-05-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaordering', '0011_base_base_descritpion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='base_descritpion',
            new_name='base_description',
        ),
    ]
